"""access keys and admin

Revision ID: 4b74e3af5538
Revises: 2c37c5362d8f
Create Date: 2026-09-13 22:23:45.046839

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b74e3af5538'
down_revision: Union[str, None] = '2c37c5362d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('batch', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['redeemed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_keys_batch'), 'access_keys', ['batch'], unique=False)
    op.create_index(op.f('ix_access_keys_code'), 'access_keys', ['code'], unique=True)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('access_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_until')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_access_keys_code'), table_name='access_keys')
    op.drop_index(op.f('ix_access_keys_batch'), table_name='access_keys')
    op.drop_table('access_keys')
    # ### end Alembic commands ###
